version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: diario_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diario_personal
      MYSQL_USER: diario_user
      MYSQL_PASSWORD: diario_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - diario_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: diario_backend
    restart: unless-stopped
    environment:
      MYSQL_HOST: database
      MYSQL_USER: diario_user
      MYSQL_PASSWORD: diario_password
      MYSQL_DB: diario_personal
      FLASK_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - diario_network
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diario_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - diario_network
    environment:
      REACT_APP_API_URL: http://localhost/api

volumes:
  mysql_data:
    driver: local

networks:
  diario_network:
    driver: bridge